export const PRODUCT_LIST_REQUEST="PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS="PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL="PRODUCT_LIST_FAIL";


export const PRODUCT_DETAILS_REQUEST="PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS="PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_FAIL="PRODUCT_FAIL";


export const CART_ADD_ITEM="CART_ADD_ITEM";
export const CART_REMOVE_ITEM="CART_REMOVE_ITEM";
export const CART_REMOVE_ALL="CART_REMOVE_ALL";
export const CART_SAVE_SHIPPING_ADDRESS="CART_SAVE_SHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD="CART_SAVE_PAYMENT_METHOD";

export const SIGNIN_REQUEST="SIGNIN_REQUEST";
export const SIGNIN_SUCCESS="SIGNIN_SUCCESS";
export const SIGNIN_FAIL="SIGNIN_FAIL";
export const SIGNOUT="SIGNOUT";


export const REGISTER_REQUEST="REGISTER_REQUEST";
export const REGISTER_SUCCESS="REGISTER_SUCCESS";
export const REGISTER_FAIL="REGISTER_FAIL";


